version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-fintech
    ports:
      - 8000:8000
    environment:
      - DB_USER=db_user
      - DB_PASSWORD=s3cr3tpassword
      - DB_NAME=grey_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - SERVER_PORT=8000
      - JWT_SECRET=jwts3cret
    restart: unless-stopped
    networks:
      - microservices_nginx_network

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=s3cr3tpassword
      - POSTGRES_DB=grey_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_nginx_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d grey_db"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  microservices_nginx_network:
    driver: bridge
    external: true
    name: microservices_nginx_network

volumes:
  postgres_data: